# Generated by Django 4.0.4 on 2023-03-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corridor',
            new_name='CorridorP',
        ),
    ]
